name: ds101
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - joblib
  - pip
  - pip:
      - jupytext
      - python-dotenv
      - black
      - flake8
